CREATE TABLE AUTHOR (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	nationality VARCHAR(255) NOT NULL,
	native_language VARCHAR(255) NOT NULL
)ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;

CREATE TABLE BOOK (
    id INT AUTO_INCREMENT PRIMARY KEY,
    author_id INT NOT NULL,
	title VARCHAR(255) NOT NULL,
	editorial VARCHAR(255) NOT NULL,
	year INT NOT NULL,
	pages INT NOT NULL,
	language VARCHAR(255) NOT NULL,
	format VARCHAR(255) NOT NULL,
	FOREIGN KEY (author_id) REFERENCES AUTHOR(id)
)ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;