CREATE TABLE PHYSICS_DETAILS (
	id INT AUTO_INCREMENT PRIMARY KEY,
	subcategory VARCHAR(255) NOT NULL,
	exercise VARCHAR(255) NOT NULL,
	answer VARCHAR(255) NOT NULL,
	book_id INT NOT NULL,
	FOREIGN KEY (book_id) REFERENCES BOOK(id)
)ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;