CREATE TABLE BOOK_ORDER (
	id INT AUTO_INCREMENT PRIMARY KEY,
	description VARCHAR(100)
)ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;

CREATE TABLE REGISTER(
	id INT AUTO_INCREMENT PRIMARY KEY,
	book_id INT NOT NULL,
	order_id INT NOT NULL,
	FOREIGN KEY (book_id) REFERENCES BOOK(id),
	FOREIGN KEY (order_id) REFERENCES BOOK_ORDER(id)
)ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;